apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - applications/full-stack-app.yaml
  - backend/
  - frontend/ 
  - postgres/
  - monitoring/
  - networking/

# Optionnel : patches pour l'environnement local
patches:
  - target:
      kind: Deployment
      name: ".*"
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
